### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by arm61** [rhayes777/PyAutoFit#123]
In the "fitting a model" docs the object `m.Gaussian` is used, I assume this should be the `Gaussian` class defined earlier?

**Comment by arm61** [comment]
Similar with `a.Analysis` in the next line.

**Comment by Jammy2211** [comment]
You're correct, will fix that now.

There may be a subtlety where not using the .m for the Gaussian messes with the config files (this is why the examples import it separately). We wrote the autofit readthedocs as an API overview to 'hook people in' rather than something one copy and pastes to get started (we imagined the examples / howtofit would be used for that).

If you're using the readthedocs to do this though, it suggests we should make them useable in that way. In hindsight its a bit dumb that they're not.

**Comment by arm61** [comment]
Yeah, my first instinct was to start "copy and pasting" from the Overview section (basically as soon as I say some code!). I have not realised the separation that the Tutorials create and am working from them.

**Comment by Jammy2211** [comment]
I have updated these typos - they may not work as intended yet due to config issues which arn't worth explaining. However, we have a big refactor which will make all configs optional coming soon, negating this issue, so it should be fine for now!

I've also added text to each section encouraging users to checkout the 'examples' folder in the workspace. So, the next can be copy and pasted from here on, but hopefully we direct people in the right direction!
