### ISSUE TITLE
Round parameters of grid search folder names to 2 dp

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#13]
The folders for my grid search are titled as follows:

centre_0_-2.0_-1.3333333333333335_centre_1_-1.3333333333333335_-0.6666666666666667

Whilst I care about precsion, I dont care to 12dp.

**Comment by rhayes777** [comment]
Haha I'll round those... Sent from my Huawei Mobile-------- Original Message --------Subject: [rhayes777/PyAutoFit] Round parameters of grid search to 2 dp (#13)From: James Nightingale To: rhayes777/PyAutoFit CC: Subscribed The folders for my grid search are titled as follows:
centre_0_-2.0_-1.3333333333333335_centre_1_-1.3333333333333335_-0.6666666666666667
Whilst I care about precsion, I dont care to 12dp.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rhayes777/PyAutoFit","title":"rhayes777/PyAutoFit","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/rhayes777/PyAutoFit"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Round parameters of grid search to 2 dp (#13)"}],"action":{"name":"View Issue","url":"https://github.com/rhayes777/PyAutoFit/issues/13"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rhayes777/PyAutoFit/issues/13",
"url": "https://github.com/rhayes777/PyAutoFit/issues/13",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
