### ISSUE TITLE
"Long" times to access pickles on first go?

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#309]
I have created a tool to profile the database at the following link:

`https://github.com/Jammy2211/autofit_workspace_test/tree/main/database/profiling`

Queries are super fast, yay!

One thing I've noted is that the first access of pickles via the database (irrespective of the filesize of that pickle) can be very slow:

```
agg = af.Aggregator.from_database("profiling.sqlite")

start = time.time()
agg.values("model")
print(f"Time to load model via pickle {time.time() - start} \n")

start = time.time()
agg.values("samples")
print(f"Time to load samples via pickle {time.time() - start} \n")

start = time.time()
agg.values("search")
print(f"Time to load search via pickle {time.time() - start} \n")
```

Here are the run times:

```
Time to load model via pickle 22.8411648273468

Time to load samples via pickle 1.3832511901855469

Time to load search via pickle 0.008813858032226562
```

Whatever is first is significantly slower than anything after it. This is OK, kind of, but for large databases can lead to very prohibitive run times for quick queries.

**Comment by rhayes777** [comment]
That's really odd. It makes sense that it should take time for large sets of results because it's deserialising a lot of objects. I'm not sure why it should be faster for samples and search though.

Have you tried loading models after loading samples and searches?

**Comment by Jammy2211** [comment]
It seems like the overhead is there irrespective of what I load, and what order I load it in.

**Comment by rhayes777** [comment]
Do you have the sqlite file?

**Comment by rhayes777** [comment]
This is because of lazy loading of attributes.

A query gets ids for the fits you want, then another query grabs Fit objects. These are basically just wrappers for the id - the database isn't queried for more data until an attribute of a fit is required. When you request models, queries are executed for all of the fits.

We could change the loading strategy so that pickles are eagerly loaded. This would mean that only one trip to the database is made (rather than 250). However, this would also mean a lot of data in memory and make the initial loading slower.

We could also make the result of a call to values a generator, such that data is only loaded when it is required.

Ultimately these are all just tradeoffs.

**Comment by rhayes777** [comment]
I've changed to joined loading of pickles. Let's see how it goes
