### ISSUE TITLE
Only create dynasty plots at the end of a fit 

### ISSUE THREAD

**Issue by Findus23** [rhayes777/PyAutoFit#746]
Creating the dynasty cornerplot and traceplot is quite computationally expensive and takes multiple seconds.
By default, `iterations_per_update` is set to 500 which means that in a very simple example, dynasty only runs for a few milliseconds before pausing, saving and then plotting for a while.

While one could increase `iterations_per_update` to a huge number (like `1_000_000_000_000`) to speed up the runtime significantly, but this works slightly weird (it still creates the plot more than once).

So it would be great if there was a setting (in `visualize.yaml`?) to only create plots once at the end of a fit (and maybe enable it by default to speed up all simple examples).

Slight tangent: A lot of scientific software I know saves intermediate snapshots every X minutes (wallclock-time) instead of iterations to avoid this issue (as you make the backups to not lose the last X minutes of work independent of how many steps there were). So maybe that would be a way to avoid this whole issue.

**Comment by Jammy2211** [comment]
Its always been a struggle to decide how and when to do updates.

If your likelihood evaluation time is very fast (as it was in the workshop) then doing it per iterations can lead to a lot of output, which slows things down.

If the evaluation time is slow (as it is in many Astronomy applications), then doing it based on wallclock-time has issues, as you end up updating things even though the fit has not progressed much.

I think the best solution is to document more clearly the `iterations_per_update` input, so that a user can choose a value which gives them feedback on a sensible timescale whilst not slowing down the fit too much.

We could try something more fancy that dynamically calculates when to perform updates, but this sounds complex.
