### ISSUE TITLE
Grid Search Parent losing Attributes

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#860]
We added functionality to add a `parent` to a `GridSearch` so that the log likelihoods of the previous fit can be compared:

```
parent = af.DynestyStatic(name="parent")

parent.fit(model=model, analysis=analysis)

grid_search = af.SearchGridSearch(search=search, number_of_steps=2, number_of_cores=1)

grid_search_result = grid_search.fit(
    model=model, analysis=analysis, grid_priors=[model.gaussian.centre], parent=parent
)
```

The attributes of the `parent` are no longer being passed correct and are not accessible:

```
for fit in agg.grid_searches().best_fits():
    print(f"Grid Search Parent (fit.parent): {fit.parent}")

    assert fit.parent is not None
    assert fit.parent.samples is not None
    assert fit.parent.instance is not None
```

The `samples` and `instance` should correspond to the result of the `parent` fit.

This script can be used to test and fix the issue:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/scripts/database/scrape/grid_search.py

**Comment by rhayes777** [comment]
This is fixed in https://github.com/rhayes777/PyAutoFit/pull/862

There are a couple of issues with that script:
1) The aggregator does not add the directory containing the parent fit. That should be changed to include everything. e.g.:
```python
agg.add_directory(directory="output")
```
2) It iterates through best fits. The parent of each best fit is the grid search. I assume you wanted the parent of the grid search:
```python
for fit in agg.grid_searches():
    print(f"Grid Search Parent (fit.parent): {fit.parent}")

    assert fit.parent is not None
    assert fit.parent.samples is not None
    assert fit.parent.instance is not None
