### ISSUE TITLE
Interpolate Functionality not wokring in Certain circumstances

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#896]
The following example script illustrates interpolation functionality working in autofit:

https://github.com/Jammy2211/autofit_workspace/blob/main/scripts/features/interpolate.py

The key point is that the interpolation at the end correctly infers the centre at t=1.5 is 55 pixels:

```
Gaussian centre of fit 1 (t = 1): 39.98318612575531
Gaussian centre of fit 2 (t = 2): 49.71884489059448
Gaussian centre interpolated at t = 1.5 54.83994657794634
```

The following PyAutoCTI example uses the same functionality to interpolate a CTI model and try determine a trap density:

https://github.com/Jammy2211/autocti_workspace/blob/main/scripts/dataset_1d/advanced/temporal/fit.py

However, the interpolation at the end is wrong, and just repeats the t=1 value:

```
Trap density of fit 1 (t = 1): 0.93416064977646
Trap density of fit 2 (t = 2): 1.198615655303
Trap Density interpolated at t = 1.5 0.93416064977646
```

The model results are correct (the densities inferred for each time are spaced correctly over time).

I think that there is a bug due to a mix of a specific type of model composition, and the interpolator not handling this correctly.

**Comment by rhayes777** [comment]
This is because `trap_list` is a property of `CTI1D` which in turn accesses the `_trap_list` attribute. Model intraspection ignores attributes starting with an underscore so that special attributes such as the model id or cache are not included.

We could make some rule where if a private attribute has a public property with the same name then it is included. Alternatively we could insist that any model associated attributes of model classes must be public.

**Comment by Jammy2211** [comment]
I honestly have no idea why `_trap_list` is a private attribute so will just update the `PyAutoCTI` code.
